# Site settings
title: TheGoFind Blog
url: "http://thegofind.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" 
description: >
  One or more sentences introducing this blog.

# Your information
email: 43659894@qq.com
author: TheGoFind
avatar: "http://github.com/thegofind/thegofind.github.io/raw/master/img/avatar.png"
profile: Hi, this is Chen HaoRan. Welcome to my blog. I hope you will enjoy it.
homepage_username: thegofind
github_username:  thegofind

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: thegofind   
# get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
